package com.gestureworks.cml.core
{	
	import com.gestureworks.cml.elements.Container;
	import com.gestureworks.cml.utils.DefaultStage;
	import com.gestureworks.core.GestureWorks;
	
	/**
	 * The CMLDisplay class is the root container for a display generated by CML.
	 * 
	 * @author Ideum
	 * @see com.gestureworks.cml.core.CMLParser
	 * @see com.gestureworks.cml.core.CMLObjectList
	 */
	public class CMLDisplay extends Container
	{
		/**
		 * Constructor
		 */
		public function CMLDisplay()
		{			
			super();
		}
		
		/**
		 * Initialization method
		 * @param	cml
		 */
		public function initialize(cml:XML):void 
		{	
			DefaultStage.instance.stage = GestureWorks.application.stage;		
			CMLParser.init(cml, this);			
		}

	}
}