package com.gestureworks.cml.core
{	
	import com.gestureworks.cml.core.*;
	import com.gestureworks.core.GestureWorks;
	import com.gestureworks.utils.*;
	import com.gestureworks.cml.utils.*;
	import flash.display.*;
	import flash.events.*;
	
	/**
	 * The CMLDisplay class is the root container for a display generated by CML.
	 * 
	 * @author Ideum
	 * @see com.gestureworks.cml.core.CMLParser
	 * @see com.gestureworks.cml.core.CMLObjectList
	 */
	public class CMLDisplay extends Sprite
	{
		/**
		 * Constructor
		 */
		public function CMLDisplay()
		{			
			super();
		}
		
		/**
		 * initialization method
		 * @param	cml
		 */
		public function init(cml:XML):void 
		{	
			removeEventListener(Event.ADDED_TO_STAGE, init);
			DefaultStage.instance.stage = GestureWorks.application.stage;			
			CMLParser.init(cml, this);			
		}

	}
}